/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root'
import { Route as DotDotDemo1IndexRouteImport } from './demo1/index'
import { Route as DotDotDemo2RouteRouteImport } from './demo2/route'
import { Route as DotDotHomeIndexRouteImport } from './home/index'
import { Route as DotDotDemo2IndexRouteImport } from './demo2/index'

const DotDotDemo1IndexRoute = DotDotDemo1IndexRouteImport.update({
  id: '/demo1',
  path: '/demo1',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDemo2RouteRoute = DotDotDemo2RouteRouteImport.update({
  id: '/demo2',
  path: '/demo2',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotHomeIndexRoute = DotDotHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDemo2IndexRoute = DotDotDemo2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DotDotDemo2RouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DotDotHomeIndexRoute
  '/demo2': typeof DotDotDemo2RouteRouteWithChildren
  '/demo1': typeof DotDotDemo1IndexRoute
  '/demo2/': typeof DotDotDemo2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DotDotHomeIndexRoute
  '/demo1': typeof DotDotDemo1IndexRoute
  '/demo2': typeof DotDotDemo2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof DotDotHomeIndexRoute
  '/demo2': typeof DotDotDemo2RouteRouteWithChildren
  '/demo1': typeof DotDotDemo1IndexRoute
  '/demo2/': typeof DotDotDemo2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo2' | '/demo1' | '/demo2/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo1' | '/demo2'
  id: '__root__' | '/' | '/demo2' | '/demo1' | '/demo2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDotHomeIndexRoute: typeof DotDotHomeIndexRoute
  DotDotDemo2RouteRoute: typeof DotDotDemo2RouteRouteWithChildren
  DotDotDemo1IndexRoute: typeof DotDotDemo1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo1': {
      id: '/demo1'
      path: '/demo1'
      fullPath: '/demo1'
      preLoaderRoute: typeof DotDotDemo1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo2': {
      id: '/demo2'
      path: '/demo2'
      fullPath: '/demo2'
      preLoaderRoute: typeof DotDotDemo2RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DotDotHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo2/': {
      id: '/demo2/'
      path: '/'
      fullPath: '/demo2/'
      preLoaderRoute: typeof DotDotDemo2IndexRouteImport
      parentRoute: typeof DotDotDemo2RouteRoute
    }
  }
}

interface DotDotDemo2RouteRouteChildren {
  DotDotDemo2IndexRoute: typeof DotDotDemo2IndexRoute
}

const DotDotDemo2RouteRouteChildren: DotDotDemo2RouteRouteChildren = {
  DotDotDemo2IndexRoute: DotDotDemo2IndexRoute,
}

const DotDotDemo2RouteRouteWithChildren =
  DotDotDemo2RouteRoute._addFileChildren(DotDotDemo2RouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DotDotHomeIndexRoute: DotDotHomeIndexRoute,
  DotDotDemo2RouteRoute: DotDotDemo2RouteRouteWithChildren,
  DotDotDemo1IndexRoute: DotDotDemo1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
